name: dart_dependency_checker_cli
description: A command-line utility for checking dependencies within Dart/Flutter packages.
repository: https://github.com/akaiser/dart_dependency_checker_cli
version: 0.5.0

executables:
  dart_dependency_checker:
  ddc:

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ^3.6.0

dependencies:
  args: ^2.6.0
  dart_dependency_checker: 0.4.2
  equatable: ^2.0.7
  yaansi: ^1.2.0

dev_dependencies:
  yaml: ^3.1.3
  build_runner: ^2.4.15
  build_version: ^2.1.1
  lints: ^5.1.1
  test: ^1.25.15
